@url = http://localhost:9091

# @name Health-check
GET {{url}}/health-check
accept: application/json
content-type: application/json

### END

# @name check test
GET {{url}}/test
accept: application/json
content-type: application/json

### END

# @name Test error
GET {{url}}/error
accept: application/json
content-type: application/json

### END
