@url = http://localhost:9091
@userId = Cj7R-WiAarxuigrNon8vs

# @name CreateUser
POST {{url}}/user
accept: application/json
content-type: application/json

{
  "userName": "test2",
  "password": "1234"
}

### END

# @name GetUserById
GET {{url}}/user/{{userId}}
accept: application/json
content-type: application/json

### END

# @name UpdateUser
PATCH {{url}}/user
accept: application/json
content-type: application/json

{
  "id": "Cj7R-WiAarxuigrNon8vs",
  "password": "123"
}

### END

# @name SoftDeleteUser
DELETE {{url}}/user/{{userId}}
accept: application/json
content-type: application/json

### END
