@url = http://localhost:9091
@userId = 1utPCfNf_EMVy3LukIKei

# @name CreateUser
POST {{url}}/user
accept: application/json
content-type: application/json

{
  "userName": "test3",
  "password": "1234"
}

### END

# @name GetUserById
GET {{url}}/user/{{userId}}
accept: application/json
content-type: application/json

### END

# @name UpdateUser
PATCH {{url}}/user
accept: application/json
content-type: application/json

{
  "id": "1utPCfNf_EMVy3LukIKei",
  "password": "12345"
}

### END

# @name SoftDeleteUser
DELETE {{url}}/user/{{userId}}
accept: application/json
content-type: application/json

### END
