version: "2.1"

services:
    mongodb:
        image: mongo:latest
        container_name: ticketing-mongodb-local
        restart: always
        ports:
            - '27017:27017'
        environment:
            TZ: Asia/Bangkok
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: ticketing

