version: "2.1"

services:
    redis:
        image: redis:7-alpine
        container_name: ticket-redis-local
        restart: always
        ports:
            - 6381:6379
        environment:
            TZ: Asia/Bangkok
            REDIS_PASSWORD: 1234
