version: "2.1"

services:
    db:
        image: mysql:8.0
        container_name: konticket-db-local
        restart: always
        ports:
            - 3308:3306
        environment:
            TZ: Asia/Bangkok
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_USER: konticket
            MYSQL_PASSWORD: 1234
            MYSQL_DATABASE: konticket

    redis:
        image: redis:7-alpine
        container_name: konticket-redis-local
        restart: always
        ports:
            - 6380:6379
        environment:
            TZ: Asia/Bangkok
            REDIS_PASSWORD: 1234

    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.2
        container_name: konticket-zookeeper-local
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka1:
        image: confluentinc/cp-kafka:7.3.2
        container_name: konticket-kafka1-local
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: konticket-zookeeper-local:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"

    kafka2:
        image: confluentinc/cp-kafka:7.3.2
        container_name: konticket-kafka2-local
        ports:
            - "9093:9093"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: konticket-zookeeper-local:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"

    mongodb:
        image: mongo:latest
        container_name: konticket-mongodb-local
        restart: always
        ports:
            - "27017:27017"
        environment:
            TZ: Asia/Bangkok
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
